package com.azu.hospital.utils.enums;

public enum Test {
    NURSING_HEAD_CHIEF("Nursing Head Chief"),
    NURSING_HEAD_CHIEF_ASSISTANT("Nursing Head Chief Assistant"),
    NURSING_STAFF_CHIEF("Nursing Staff Chief"),
    NURSING_STAFF_CHIEF_ASSISTANT("Nursing Staff Chief Assistant"),
    NURSES("Nurses"),
    NURSING_ASSISTANT("Nursing Assistant"),
    NURSE_AIDE("Nurse Aide"),
    NURSE_CLINICAL_EDUCATOR("Nurse Clinical Educator"),
    NURSE_CONSULTANT("Nurse Consultant"),
    NURSE_INFORMATICS_ANALYST("Nurse Informatics Analyst"),
    NURSE_MANAGER("Nurse Manager"),
    NURSE_MIDWIFE("Nurse Midwife"),
    NURSE_PARALEGAL("Nurse Paralegal"),
    NURSE_PRACTITIONER("Nurse Practitioner"),
    RECREATIONAL_THERAPIST("Recreational Therapist"),
    REGIONAL_SALES_MANAGER("Regional Sales Manager"),
    REGISTERED_NURSE("Registered Nurse"),
    WARD_MANAGER_ASSISTANT("Ward Manager Assistant"),
    PUBLIC_HEALTH_NURSE("Public Health Nurse"),
    PHARMACEUTICAL_SALES("Pharmaceutical Sales"),
    PHARMACY_CLERK("Pharmacy Clerk"),
    PHYSICAL_THERAPIST("Physical Therapist"),
    PHYSICAL_THERAPIST_ASSISTANT("Physical Therapist Assistant"),
    PHYSICAL_THERAPY_ASSISTANT("Physical Therapy Assistant"),
    PHYSICAL_THERAPY_MANAGER("Physical Therapy Manager"),
    PHYSICIAN_AIDE("Physician Aide"),
    PHYSICIAN_ASSISTANT("Physician Assistant"),
    PHYSICIAN_EXECUTIVE("Physician Executive"),
    ANESTHETIST_ASSISTANT("Anesthetist Assistant"),
    ANESTHETIST_TECHNICAL("Anesthetist Technical"),
    CARDIAC_CATHETERIZATION_LAB_NURSE("Cardiac Catheterization Lab Nurse"),
    CARDIOVASCULAR_OPERATING_ROOM_NURSE("Cardiovascular Operating Room Nurse"),
    CERTIFIED_NURSING_ASSISTANT("Certified Nursing Assistant"),
    CLINICAL_LIAISON("Clinical Liaison"),
    CLINICAL_NURSE_MANAGER("Clinical Nurse Manager"),
    CLINICAL_REVIEWER("Clinical Reviewer"),
    CLINICAL_SPECIALIST("Clinical Specialist"),
    ASSISTANT_DIRECTOR_OF_NURSING("Assistant Director of Nursing"),
    DENTAL_ASSISTANT("Dental Assistant"),
    DENTAL_HYGIENIST("Dental Hygienist"),
    DENTAL_LAB_TECHNICIAN("Dental Lab Technician"),
    DERMATOLOGY_NURSE("Dermatology Nurse"),
    DIALYSIS_NURSE("Dialysis Nurse"),
    DIRECTOR_OF_NURSING("Director of Nursing"),
    DIRECTOR_OF_REHABILITATION("Director of Rehabilitation"),
    EMERGENCY_ROOM_NURSE("Emergency Room Nurse"),
    ENDOSCOPY_NURSE("Endoscopy Nurse"),
    FAMILY_NURSE_PRACTITIONER("Family Nurse Practitioner"),
    INTENSIVE_CARE_NURSE("Intensive Care Nurse"),
    LABORATORY("Laboratory"),
    LAB_ANALYST("Lab Analyst"),
    LICENSED_PRACTICAL_NURSE("Licensed Practical Nurse"),
    MASSAGE_THERAPIST("Massage Therapist"),
    MEDICAL_ASSISTANT("Medical Assistant"),
    MEDICAL_ASSOCIATE("Medical Associate"),
    MEDICAL_BILLING_SPECIALIST("Medical Billing Specialist"),
    MEDICAL_CLAIMS_AND_BILLING_SPECIALIST("Medical Claims and Billing Specialist"),
    MEDICAL_OFFICE_ASSISTANT("Medical Office Assistant"),
    MEDICAL_OFFICE_MANAGER("Medical Office Manager"),
    MEDICAL_OFFICE_SPECIALIST("Medical Office Specialist"),
    MEDICAL_OR_HEALTH_SERVICES_MANAGER("Medical or Health Services Manager"),
    MEDICAL_RECORDS_DIRECTOR("Medical Records Director"),
    MEDICAL_SURGERY_NURSE("Medical Surgery Nurse"),
    MOBILE_DIRECTOR_OF_NURSING_SERVICES("Mobile Director of Nursing Services"),
    MRI_TECHNOLOGIST("MRI Technologist"),
    NEONATAL_INTENSIVE_CARE_NURSE("Neonatal Intensive Care Nurse"),
    NURSING_HOME_ADMINISTRATOR("Nursing Home Administrator"),
    ONCOLOGY_NURSE("Oncology Nurse"),
    OPERATING_ROOM_NURSE("Operating Room Nurse"),
    OPERATIONS_MANAGER("Operations Manager"),
    PEDIATRIC_INTENSIVE_CARE_NURSE("Pediatric Intensive Care Nurse"),
    PEDIATRIC_NURSE("Pediatric Nurse"),
    PEDIATRIC_NURSE_PRACTITIONER("Pediatric Nurse Practitioner"),
    PHARMACEUTICAL_SALES_REPRESENTATIVE("Pharmaceutical Sales Representative"),
    PHARMACISTS("Pharmacists"),
    PHARMACISTS_ASSISTANT("Pharmacists Assistant"),
    PROGRESSIVE_CARE_NURSE("Progressive Care Nurse"),
    PSYCHIATRIC_AIDE("Psychiatric Aide"),
    PSYCHIATRIC_NURSE("Psychiatric Nurse"),
    PSYCHIATRIC_NURSE_PRACTITIONER("Psychiatric Nurse Practitioner"),
    LAB_TECHNICAL("Lab Technical"),
    HOSPICE_ADMINISTRATOR("Hospice Administrator"),
    HOSPICE_AIDE("Hospice Aide"),
    HOSPICE_AND_PALLIATIVE_MEDICINE_SPECIALIST("Hospice and Palliative Medicine Specialist"),
    HEALTHCARE_ADMINISTRATOR("Healthcare Administrator"),
    HEALTHCARE_MANAGEMENT("Healthcare Management"),
    HEALTHCARE_SPECIALIST("Healthcare Specialist"),
    HEALTH_EDUCATOR("Health Educator"),
    HEALTH_FACILITIES_SURVEYOR("Health Facilities Surveyor"),
    HEALTH_SERVICES_MANAGER("Health Services Manager"),
    LABORATORY_BACTERIOLOGY("Laboratory Bacteriology"),
    ASSISTANT_DIRECTOR_OF_THE_LABORATORY_DIVISION("Assistant Director of the Laboratory Division");

    private final String roleName;

    Test(String roleName) {
        this.roleName = roleName;
    }

    public String getName() {
        return roleName;
    }
}
