package com.azu.hospital.utils.enums.patient;

public enum ChartTypes {
    ANESTHESIA_PHYSICIAN_ORDERS,
    BURN_DIAGRAM_CHART,
    FLUID_BALANCE_CHART,
    NEUROLOGICAL_OBSERVATION_CHART,
    NON_SEDATED_PATIENT_ASSESSMENT,
    NURSING_ASSESSMENT_CHART,
    NURSING_CARE_PLAN_CHART,
    PAIN_MANAGEMENT_CHART,
    PATIENT_ASSESSMENT_CHART,
    PATIENT_CONSENT_ANESTHESIA_CHART,
    POST_ANESTHETIC_EVALUATION_CHART,
    POST_DISCHARGE_INSTRUCTIONS_CHART,
    POST_OPERATIVE_FOLLOW_UP_CALL,
    PRE_ADVANCE_DIRECTIVE_CHART,
    PRE_ANESTHETIC_EVALUATION_CHART,
    PRE_MEDICAL_ASSESSMENT_CHART,
    PRE_OPERATIVE_HP_CHART,
    PROCEDURE_ANESTHESIA_CONSENT_CHART,
    SEDATED_PATIENT_ASSESSMENT,
    OPERATIVE_NOTE_CHART,
}

