package com.azu.hospital.Patients.charts.physical_assessment_enm;

public enum TreatmentType {
  EXERCISE,
  ACUPUNCTURE,
  HEAT_ICE,
  BIOFEEDBACK,
  MENTAL_HEALTH_PROFESSIONAL,
  STEROID_EPIDURALS,
  FACET_JOINT_INJECTIONS,
  MASSAGE,
  BRACE,
  NERVE_BLOCK,
  TENS_UNIT,
  TRACTION,
  SURGERY,
  CHIROPRACTIC_CARE,
  PHYSICAL_THERAPY,
  OCCUPATIONAL_THERAPY,
  OSTEOPATHIC_TREATMENT;
}
